FROM python:3.9.7-alpine3.14
RUN apk update
RUN apk add --no-cache bash
RUN apk add make build-base automake gcc g++ subversion python3-dev gfortran openblas-dev qt6-qtbase-dev
RUN pip install --upgrade pip
SHELL ["/bin/bash", "-i", "-c"]

LABEL maintainer="f.batonogov@yandex.ru"

ARG PYINSTALLER_VERSION=5.13.2

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY entrypoint-linux.sh /entrypoint.sh

RUN pip3 install pyinstaller==$PYINSTALLER_VERSION \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
