FROM centos:centos7.9.2009 as build
RUN yum groupinstall -y "Development Tools"
RUN yum install -y mesa-libGL pulseaudio-libs-glib2 gstreamer1-plugins-base libwayland-cursor libxkbcommon qt5-qtbase-gui libXcomposite libxkbcommon-x11 gtk3 atk gdk-pixbuf2 cairo-gobject
RUN yum install -y https://repo.ius.io/ius-release-el7.rpm
RUN yum makecache
RUN yum install -y python36u python36u-libs python36u-devel python36u-pip
RUN python3 -m pip install --upgrade pip setuptools
WORKDIR /tmp




#RUN apk update
#RUN apk add --no-cache bash
#RUN apk add make build-base automake gcc g++ subversion python3-dev gfortran openblas-dev qt5-qtbase-dev
#RUN pip install --upgrade pip


from build as compiling
SHELL ["/bin/bash", "-i", "-c"]

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY entrypoint-linux.sh /entrypoint.sh

RUN pip3 install pyinstaller  && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
